CAR (CONS (INT 5, INT 6)) NIL;

CDR (CONS (INT 5, INT 6)) NIL;

NULL NIL NIL;
NULL (INT 5) NIL;

INTEGER (INT 1000) NIL;
INTEGER (STR "ABC") NIL;

LST (CONS(CONS(INT 5, NIL), NIL)) NIL;
LST (CONS(CONS(INT 5, INT 5), NIL)) NIL;

QUOTE (CONS(EAGER (BINARY PLUS), CONS(INT 5, CONS(INT 7, NIL)))) NIL;
QUOTE (STR "AB") NIL;

EQ (CONS(STR "A", INT 6), CONS(STR "B", INT 6)) NIL;
EQ (STR "&", STR "&") NIL;

PLUS (INT 5, INT 7) NIL;

TIMES (INT 5, INT 7) NIL;

MEANING (STR "A", CONS(CONS(STR "A", INT 5), CONS(CONS(STR "B", INT 8), NIL))) NIL;

EVAL (CONS (EAGER (BINARY PLUS), CONS (INT 5, CONS (INT 7, NIL))), NIL);
EVAL (CONS (NORMAL (UNARY QUOTE), CONS (STR "A", NIL)), CONS (CONS (STR "A", INT 5), NIL));

COND(CONS(NORMAL (UNARY QUOTE), CONS(T, NIL)), INT 5, STR "7") (CONS(CONS(STR "7", INT 14), NIL));

SETQ (STR "B", INT 67) (CONS (CONS (STR "A", INT 56), NIL));
